### ISSUE TITLE
We miss a default Site (settings.SITE_ID should not be None)

### ISSUE THREAD

**Issue by olivierdalang** [yverdon/geocity#525]
Currently, SITE_ID is set to None in settings, meaning that unless the request matches an existing Site object, we get an error.

This is problematic, because there can be multiple hosts that should refer to the default site site (localhost, 127.0.0.1, web...), so we should not create an entry for each one.

IMO we should have a SITE_ID set, an use a custom `CurrentSiteMiddleware` that overrides the current site if there is a match, and keeps the default otherwise.

(while at it, we could probably also remove the `SetCurrentSiteMixin` mixin, which does not seem alright)

**Comment by monodo** [comment]
Moved to Jira @olivierdalang
