### ISSUE TITLE
BUG: Change map scale or units

### ISSUE THREAD

**Issue by nicolas-sitylb** [yverdon/geocity#56]
it's currently a _little_ wrong:    

![image](https://user-images.githubusercontent.com/61550003/80456704-57a2a800-892e-11ea-9bd6-1aa530ed9138.png)

**Comment by monodo** [comment]
Such a tiny detail ;-)

**Comment by monodo** [comment]
Here is the problem: https://github.com/yverdon/geocity/blob/nbc-dev-YGDP-8/static/customWidgets/GeometryWidget/geometrywidget.js#L157

**Comment by monodo** [comment]
Fixed in https://github.com/yverdon/geocity/pull/62
