### ISSUE TITLE
Unable to spin-up the app on a local server: `Exception Value: Site matching query does not exist.`

### ISSUE THREAD

**Issue by nicolas-heigvd** [yverdon/geocity#608]
Hello,

I am facing an issue when trying to set up the app (from the `main` branch) on an local server (i.e. a VM on a local infrastructure).

All migrations went fine but I had to manually execute them.

Here's the trace:

```
Environment:


Request Method: GET
Request URL: http://geocity.<local-server-name>.ch:9095/

Django Version: 3.2.15
Python Version: 3.8.10
Installed Applications:
['geocity.apps.core',
 'geocity.apps.accounts',
 'geocity.apps.accounts.geomapfish',
 'geocity.apps.accounts.dootix',
 'geocity.apps.reports',
 'geocity.apps.forms',
 'geocity.apps.submissions',
 'geocity.apps.permits',
 'grappelli',
 'polymorphic',
 'adminsortable2',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'constance',
 'constance.backends.database',
 'simple_history',
 'corsheaders',
 'django_filters',
 'rest_framework',
 'rest_framework_gis',
 'knox',
 'bootstrap4',
 'bootstrap_datepicker_plus',
 'django_tables2',
 'django_tables2_column_shifter',
 'taggit',
 'oauth2_provider',
 'crispy_forms',
 'django_cron',
 'axes',
 'captcha',
 'ckeditor',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'django.contrib.sites',
 'django.contrib.postgres',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'axes.middleware.AxesMiddleware',
 'django.contrib.sites.middleware.CurrentSiteMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/sites/models.py", line 39, in _get_site_by_request
    SITE_CACHE[host] = self.get(domain__iexact=host)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Site matching query does not exist.), another exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/sites/middleware.py", line 12, in process_request
    request.site = get_current_site(request)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
    return Site.objects.get_current(request)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/sites/models.py", line 60, in get_current
    return self._get_site_by_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/sites/models.py", line 45, in _get_site_by_request
    SITE_CACHE[domain] = self.get(domain__iexact=domain)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /
Exception Value: Site matching query does not exist.

```

Maybe this is related (?):    
Inspired by the [doc](https://github.com/yverdon/geocity#default-site), the `DEFAULT_SITE`  env var has been set to: `<local-server-name>.ch`, while  `geocity.<local-server-name>.ch` has been appended to the `ALLOWED_HOSTS` env var.
The same error occurs if I change the `DEFAULT_SITE`  to: `geocity.<local-server-name>.ch` and/or `ALLOWED_HOSTS` to: `<local-server-name>.ch`. Actually, all possible 4 combinations were tested without any success.

The server is running Ubuntu 22.04.1 LTS.

How can I solve this issue?

Many thanks for your help.

**Comment by nicolas-sitylb** [comment]
Hi,

thanks for the reporting.

Can you tell us the result of the following PostgreSQL command run on the containerized database :
`SELECT * FROM geocity.django_site;` 
?

**Comment by nicolas-heigvd** [comment]
Thanks.

It looks like this:

```
geocity=# SELECT * FROM public.django_site;
 id |  domain   |         name         
----+-----------+----------------------
  1 | web       | web (internal calls)
  2 | localhost | default site
(2 rows)
```

**Comment by nicolas-sitylb** [comment]
What was the order of the operations you did?
Did you by any chance, started the application before making changes and/or updating the `.env` file?

**Comment by nicolas-heigvd** [comment]
According to the flow in the doc, here is what I precisely did, in a chronological order:
1. I've set up the `COMPOSE_FILE=docker-compose.yml` in the `.env` file
2. I ran: `docker-compose up --build -d --remove-orphans`
3. At this stage I faced this error when trying to hit the website at : `http://geocity.<local-server-name>.ch`:
```
Invalid HTTP_HOST header: 'geocity.<local-server-name>.ch'. You may need to add 'geocity.<local-server-name>.ch' to ALLOWED_HOSTS.
```

4. As suggested by this error message, I append  `geocity.<local-server-name>.ch` to the `ALLOWED_HOSTS` var in the `.env` and re-up the containers.
5. I then encountered the error mentioned in my original post: `Site matching query does not exist.`
6. So, I added `<local-server-name>.ch` to the `DEFAULT_SITE` env var; -> it didn't change anything.
7. I also tried to add `geocity.<local-server-name>.ch` instead; -> always the same error.

At this stage, I also tried to run `makemigrations` but it says: `No changes detected`,
and the output of the `SELECT * FROM public.django_site;` command is the same as above.

**Comment by nicolas-sitylb** [comment]
It seems that the changes you made in the `DEFAULT_SITE` env var were not taken into account.

As you seem to be starting a new project from scratch, and **only if** the loss of the database content is not a big concern, you can try deleting the volumes after making changes to the `DEFAULT_SITE` environment variable using: `docker-compose down --volumes`?

Otherwise, if it's a concern, you can try adding the default site with the following procedure:
1. Log into a Python shell in the application container: 
```
docker compose exec web python3 manage.py shell
```
2. Then, from the Python shell inside the container, run the following commands:
```
from django.contrib.sites.models import Site
site = Site.objects.create(domain='<local-server-name>.ch', name='my local geocity instance')
site.save()
exit()

```

3. Finally, check that the site was correctly added to the database with the same query as before: `SELECT * FROM public.django_site;` in the PostgreSQL container.

4. Try reaching the site again.

If by any chance this didn't work, try with:
```
site = Site.objects.create(domain='geocity.<local-server-name>.ch', name='my local geocity instance')
```
instead and keep us informed of the results.

**Comment by nicolas-heigvd** [comment]
Okay, 

the two proposed methods work very well, either:

1. Rebooting the application after having deleted the volumes, or:
2. Setting the site domain from the Python shell


But they **only** work with the `DEFAULT_SITE` env var (or `domain`) set to: `geocity.<local-server-name>.ch`  and **NOT** when it is set to: `<local-serrver-name>.ch`

I'm wondering why?

Anyway, it's working now, thanks a lot for the advice!

**Comment by nicolas-sitylb** [comment]
Good to hear, thanks for the feedback @nicolas-heigvd!

----

@AlexandreJunod or @sephii is there anything we can do to fix this problem? E.g., that the migration which sets the domain in the `django_site` table can actually be executed _after_ the containers have already been started?

**Comment by sephii** [comment]
@nicolas-sitylb there are 2 things:

1. `ALLOWED_HOSTS` need to contain fully qualified domain names, or prefix the domain name with a dot to allow subdomains. [The Django docs](https://docs.djangoproject.com/en/3.2/ref/settings/#allowed-hosts) mention the following:

> Values in this list can be fully qualified names (e.g. 'www.example.com'), in which case they will be matched against the request’s Host header exactly (case-insensitive, not including port). A value beginning with a period can be used as a subdomain wildcard: '.example.com' will match example.com, www.example.com, and any other subdomain of example.com. A value of '*' will match anything; in this case you are responsible to provide your own validation of the Host header (perhaps in a middleware; if so this middleware must be listed first in [MIDDLEWARE](https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-MIDDLEWARE)).

2. The default site is created in a migration, so you indeed need to drop the database (eg. by removing the volumes) if you change the value of `DEFAULT_SITE`.

This is also related to https://github.com/yverdon/geocity/issues/525, as having a default site could help mitigate this issue.

Also this made be realize we need to backport the migration that creates the default site, since it’s currently in the `permits` app, which should disappear soon.

**Comment by monodo** [comment]
The migration has been backported

**Comment by monodo** [comment]
> that the migration which sets the domain in the `django_site` table can actually be executed _after_ the containers have already been started?

This is the case
