### ISSUE TITLE
EHN: Fix geometryCollection processing when features were saved

### ISSUE THREAD

**Issue by nicolas-sitylb** [yverdon/geocity#61]
geometryCollection (after saving):    

![image](https://user-images.githubusercontent.com/61550003/80513752-cf4cf300-897f-11ea-96ff-c7ee95861f20.png)

vs single feature (before saving):

![image](https://user-images.githubusercontent.com/61550003/80513854-f9061a00-897f-11ea-8e65-1b131ef03280.png)

**Comment by monodo** [comment]
Fixed here: https://github.com/yverdon/geocity/pull/62
