### ISSUE TITLE
Printing of punctual coordinates

### ISSUE THREAD

**Issue by rogermaurer** [yverdon/geocity#765]
The output for printing of punctual coordinates gives a list of 5 pairs of coordinates.
If there is only one point digitized, the liste looks like the next example:
'coordinates':
[[[2527094.02, 1151590.9], [2527094.02, 1151592.9], [2527096.02, 1151592.9], [2527096.02, 1151590.9], [2527094.02, 1151590.9]]

The best solution would be an output only for the digitized feature.
But even in this optimal case it should be possible to select only 1 pair of coordinate from the list for printing.

**Comment by monodo** [comment]
One solution:

```
{{(coordinate[0]|round|string)[:-2]}}, {{(coordinate[1]|round|string)[:-2]}}
{% endif %}{% endfor %}{% endfor %}
{% endif %} {% if loop.index0 == 9 %}
```
